<a href="https://colab.research.google.com/github/Guliko24/CE880_Case_Study/blob/main/CE880_Case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving data_PostNatal.xlsx to data_PostNatal.xlsx

In [16]:
import pandas as pd
data= "/content/data_PostNatal.xlsx"
df=pd.read_excel(data)
df.head()

,Age,Feeling sad or Tearful,Irritable towards baby & partner,Trouble sleeping at night,Problems concentrating or making decision,Overeating or loss of appetite,Feeling of guilt,Problems of bonding with baby,Suicide attempt,Feeling anxious
0,35-40,Yes,Yes,Two or more days a week,Yes,Yes,No,Yes,Yes,Yes
1,40-45,Yes,No,No,Yes,Yes,Yes,Yes,No,No
2,35-40,Yes,No,Yes,Yes,Yes,No,Sometimes,No,Yes
3,35-40,Yes,Yes,Yes,Yes,No,Maybe,No,No,Yes
4,40-45,Yes,No,Two or more days a week,Yes,No,No,Yes,No,Yes

Let's do some exloratory data analysis

In [24]:
# quick look to data
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# from pd.tools import plotting
from scipy import stats
plt.style.use("ggplot")
import warnings
warnings.filterwarnings("ignore")
from scipy import stats

df.describe()

,Age,Feeling sad or Tearful,Irritable towards baby & partner,Trouble sleeping at night,Problems concentrating or making decision,Overeating or loss of appetite,Feeling of guilt,Problems of bonding with baby,Suicide attempt,Feeling anxious
count,1503,1503,1497,1503,1491,1503,1494,1503,1503,1503
unique,5,3,3,3,3,3,3,3,3,2
top,40-45,Yes,Yes,Two or more days a week,No,No,No,No,No,Yes
freq,364,536,555,640,583,841,624,557,709,980

In [25]:
df.isna().sum()

Age                                           0
Feeling sad or Tearful                        0
Irritable towards baby & partner              6
Trouble sleeping at night                     0
Problems concentrating or making decision    12
Overeating or loss of appetite                0
Feeling of guilt                              9
Problems of bonding with baby                 0
Suicide attempt                               0
Feeling anxious                               0
dtype: int64

In [32]:
x = df.loc[:, df.columns != 'Feeling anxious']
y = df.loc[:, 'Feeling anxious']
print(x.shape, y.shape)

(1503, 9) (1503,)

In [33]:
x

,Age,Feeling sad or Tearful,Irritable towards baby & partner,Trouble sleeping at night,Problems concentrating or making decision,Overeating or loss of appetite,Feeling of guilt,Problems of bonding with baby,Suicide attempt
0,35-40,Yes,Yes,Two or more days a week,Yes,Yes,No,Yes,Yes
1,40-45,Yes,No,No,Yes,Yes,Yes,Yes,No
2,35-40,Yes,No,Yes,Yes,Yes,No,Sometimes,No
3,35-40,Yes,Yes,Yes,Yes,No,Maybe,No,No
4,40-45,Yes,No,Two or more days a week,Yes,No,No,Yes,No
...,...,...,...,...,...,...,...,...,...
1498,30-35,Yes,No,Two or more days a week,No,No,Maybe,Sometimes,No
1499,25-30,Sometimes,No,No,Often,No,Maybe,Yes,No
1500,25-30,No,Sometimes,Two or more days a week,No,No,Yes,No,Not interested to say
1501,25-30,No,Sometimes,Yes,Often,No,No,No,No
1502,45-50,Sometimes,Sometimes,Two or more days a week,No,No,Maybe,No,No

Let's do some correlation matrix before attempting PCA

In [31]:
# Compute the correlation matrix before doing PCA
nm=pd.DataFrame(x)
pca_corr=nm.corr()
print(pca_corr)
sns.heatmap(pca_corr, vmax=1, center=0, square=True)
plt.savefig('CORR_PCA.png', dpi=300)

Empty DataFrame
Columns: []
Index: []

ValueError: zero-size array to reduction operation fmin which has no identity

In [36]:
x.corr()

Empty DataFrame
Columns: []
Index: []